server:
  port: 9090
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: binqing
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parity?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password:
  data:
    mongodb:
      uri: mongodb://localhost/parity
  mvc:
    view:
      prefix: /
      suffix: .jsp
  thymeleaf:
    enabled: false